module.exports = [
    {
        sequence: 1,
        image: "/assets/products/apple_honeycrisp.jpeg",
        title: 'Apple Honeycrisp',
        price: 2.59,
        salePrice: 1.99,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f76',
    },
    {
        sequence: 2,
        image: "/assets/products/pear_bartlett.png",
        title: 'Bartlett Pear',
        price: 2.59,
        salePrice: 1.59,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f76',
    },
    {
        sequence: 3,
        image: "/assets/products/peach.png",
        title: 'Large Peach',
        price: 3.69,
        salePrice: 2.59,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f7b',
    },
    {
        sequence: 4,
        image: "/assets/products/kiwi.png",
        title: 'Kiwi',
        price: 0.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 5,
        image: "/assets/products/passionfruit.png",
        title: 'Passion Fruit',
        price: 1.99,
        salePrice: 1.49,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 6,
        image: "/assets/products/jumbo_papaya.png",
        title: 'Jumbo Papaya',
        price: 6.59,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 7,
        image: "/assets/products/avocato.png",
        title: 'Avocato',
        price: 1.49,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 8,
        image: "/assets/products/mango.png",
        title: 'Mango',
        price: 3.49,
        salePrice: 1.99,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 9,
        image: "/assets/products/mangosteen.png",
        title: 'Mangosteen',
        price: 6.49,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 10,
        image: "/assets/products/banana.png",
        title: 'Banana',
        price: 1.59,
        salePrice: 0.79,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f77',
    },
    {
        sequence: 11,
        image: "/assets/products/young_coconut.png",
        title: 'Young Coconut',
        price: 5.99,
        salePrice: 2.99,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 12,
        image: "/assets/products/brown_coconut.png",
        title: 'Brown Coconut',
        price: 1.59,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 13,
        image: "/assets/products/blueberries.png",
        title: 'Blueberries',
        price: 5.99,
        salePrice: 0,
        unit: 1,
        measure: 312,
        measureUnit: 'g',
        category: '65c8433491a7e6baac0c9f78',
    },
    {
        sequence: 14,
        image: "/assets/products/cherries.png",
        title: 'Cherries',
        price: 5.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f78',
    },
    {
        sequence: 15,
        image: "/assets/products/organic_blackberries.png",
        title: 'Organic Blackberries',
        price: 5.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f78',
    },
    {
        sequence: 16,
        image: "/assets/products/organic_raspberries.png",
        title: 'Organic Raspberries',
        price: 5.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f78',
    },
    {
        sequence: 17,
        image: "/assets/products/raspberries.jpeg",
        title: 'Raspberries',
        price: 4.99,
        salePrice: 3.99,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f78',
    },
    {
        sequence: 18,
        image: "/assets/products/large_red_grapes.png",
        title: 'Large Red Grapes',
        price: 6.99,
        salePrice: 5.99,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f79',
    },
    {
        sequence: 19,
        image: "/assets/products/green_seedless_grapes.png",
        title: 'Green Seedless Grapes',
        price: 3.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f79',
    },
    {
        sequence: 20,
        image: "/assets/products/cotton_candy_green_grapes.png",
        title: 'Cotton Candy Green Grapes',
        price: 7.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f79',
    },
    {
        sequence: 21,
        image: "/assets/products/red_seedless_grapes.png",
        title: 'Red Seedless Grapes',
        price: 5.99,
        salePrice: 3.99,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f79',
    },
    {
        sequence: 22,
        image: "/assets/products/orange.png",
        title: 'Orange',
        price: 5.99,
        salePrice: 3.99,
        unit: 1,
        measure: 1,
        measureUnit: 'bag',
        category: '65c8433491a7e6baac0c9f7a',
    },
    {
        sequence: 23,
        image: "/assets/products/lime.png",
        title: 'Lime',
        price: 0.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7a',
    },
    {
        sequence: 24,
        image: "/assets/products/lemon.png",
        title: 'Lemon',
        price: 2.99,
        salePrice: 0,
        unit: 3,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7a',
    },
    {
        sequence: 25,
        image: "/assets/products/grapefruit.png",
        title: 'Grapefruit',
        price: 0.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7a',
    },
    {
        sequence: 26,
        image: "/assets/products/black_plum.jpeg",
        title: 'Black Plum',
        price: 0.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7b',
    },
    {
        sequence: 27,
        image: "/assets/products/nectarine.jpeg",
        title: 'Nectarine',
        price: 3.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'lb',
        category: '65c8433491a7e6baac0c9f7b',
    },
    {
        sequence: 28,
        image: "/assets/products/large_nectarine.jpeg",
        title: 'Large Nectarine',
        price: 1.50,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7b',
    },
    {
        sequence: 29,
        image: "/assets/products/mini_seedless_watermelon.jpeg",
        title: 'Mini Seedless Watermelon',
        price: 5.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7c',
    },
    {
        sequence: 30,
        image: "/assets/products/jumbo_cantaloupe.jpeg",
        title: 'Jumbo Cantaloupe',
        price: 5.99,
        salePrice: 3.99,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7c',
    },
    {
        sequence: 31,
        image: "/assets/products/honeydew.jpeg",
        title: 'Honeydew',
        price: 4.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7c',
    },
    {
        sequence: 32,
        image: "/assets/products/santa_claus_melon.jpeg",
        title: 'Santa Claus Melon',
        price: 5.79,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7c',
    },
    {
        sequence: 33,
        image: "/assets/products/canary_melon.jpeg",
        title: 'Canary Melon',
        price: 6.79,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7c',
    },
    {
        sequence: 34,
        image: "/assets/products/plantain.jpeg",
        title: 'Plantain',
        price: 0.79,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7c',
    },
]