module.exports = [
    {
        sequence: 1,
        image: "/assets/products/apple_honeycrisp.jpeg",
        title: 'Apple Honeycrisp',
        price: 2.59,
        salePrice: 1.99,
        unit: 1,
        measure: 1,
        measureUnit: 'LB',
        category: '65c8433491a7e6baac0c9f76',
    },
    {
        sequence: 2,
        image: "/assets/products/pear_bartlett.png",
        title: 'Bartlett Pear',
        price: 2.59,
        salePrice: 1.59,
        unit: 1,
        measure: 1,
        measureUnit: 'LB',
        category: '65c8433491a7e6baac0c9f76',
    },
    {
        sequence: 3,
        image: "/assets/products/peach.png",
        title: 'Large Peach',
        price: 3.69,
        salePrice: 2.59,
        unit: 1,
        measure: 1,
        measureUnit: 'LB',
        category: '65c8433491a7e6baac0c9f7b',
    },
    {
        sequence: 4,
        image: "/assets/products/kiwi.png",
        title: 'Kiwi',
        price: 0.99,
        salePrice: 0,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
    {
        sequence: 5,
        image: "/assets/products/passionfruit.png",
        title: 'Passion Fruit',
        price: 1.99,
        salePrice: 1.49,
        unit: 1,
        measure: 1,
        measureUnit: 'each',
        category: '65c8433491a7e6baac0c9f7d',
    },
]